#
# Travis CI config
# https://docs.travis-ci.com/user/customizing-the-build/
#
env:
  - COVERALLS_ENV=production

branches:
  only:
    - master

language: node_js

node_js:
  - "11.2.0"

cache:
  directories:
    - "node_modules"

script:
  - npm run lint
